### ISSUE TITLE
Extension will result in syntax errors with PHP 7.3

### ISSUE THREAD

**Issue by sypets** [b13/xray#1]
https://github.com/b13/xray/blob/8d50ad6200dfa2d0ee4c94b9a5c01c9d3a075486/Classes/ExternalLinks/ExternalLink.php#L70

`protected string $baseUrl;`

will result in syntax error with PHP < 7.4. 

```
php -l Classes/ExternalLinks/ExternalLink.php 
PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in Classes/ExternalLinks/ExternalLink.php on line 70
```
Errors parsing Classes/ExternalLinks/ExternalLink.php

----

If that is changed, rest of extension is PHP 7.3 compatible as far as I could tell.

----

Might be best to either change that or add PHP version constraints (since TYPO3 10 still supports 7.3 and even 7.2 - thought that is EOL).

**Comment by ervaude** [comment]
Hi @sypets,
thanks for reporting.

Yes that's an error, the extension should be PHP 7.3 compatible
